---
- name: Make Ansible Facts directory
  file: path=/etc/ansible/facts.d state=directory

- name: Install Postgres
  yum: name={{ item }} state=installed
  with_items:
   - postgresql95
   - postgresql95-libs
   - postgresql95-devel
   - postgresql95-server
   - postgresql95-contrib
   - python-psycopg2
   - perl-Digest-SHA

- name: Make Ansible Facts directory
  file: path=/etc/facts.d state=directory

- name: Install recovery template
  template: src=pg_recovery_template.conf.j2 dest=/usr/local/etc/pg_recovery_template.conf

- name: Initialise the DB server
  command: creates=/var/lib/pgsql/9.5/data/PG_VERSION  /usr/pgsql-9.5/bin/postgresql95-setup initdb

# This include sets up the following variables:
#  - postgres_status: Is this server a master or slave?
#  - postgres_master: Which server is the master?
- include: get_status.yml

- include: master.yml
  when: postgres_status == "master"

- include: slave.yml
  when: postgres_status == "slave"

- name: Install custom fact
  copy: src=postgres.fact dest=/etc/ansible/facts.d/postgres.fact mode=0755

