---
- name: Configure Postgres
  template: src={{ item }}.j2 dest=/var/lib/pgsql/9.5/data/{{ item }} owner=postgres group=postgres mode=600
  with_items:
   - postgresql.conf
   - pg_hba.conf
  notify: restart postgres

- name: Remove the recovery file if it exists
  file: path=/var/lib/pgsql/9.5/data/recovery.conf state=absent

- name: Start Postgres
  service: name=postgresql-9.5 state=started enabled=yes

- name: Create Postgres Replication User
  postgresql_user:
    name: repl
    password: replpass
    role_attr_flags: REPLICATION
  sudo_user: postgres

- name: Make sure required databases exist
  postgresql_db:
    name: "{{ item.value.db|default('postgres') }}"
  with_dict: postgres_users
  sudo_user: postgres

- name: Create requested users
  postgresql_user:
    name: "{{ item.key }}"
    encrypted: yes
    password: "{{ item.value.enc_pass }}"
    db: "{{ item.value.db|default('postgres') }}"
    role_attr_flags: "{{ item.value.roles|default('') }}"
  with_dict: postgres_users
  sudo_user: postgres

